robot5:
   #Publish all joint states -----------------------------------
  /robot5/joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60  

  # Velocity Controllers ---------------------------------------

  /robot5/wheel_fl_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: FL_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  /robot5/wheel_fr_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: FR_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  /robot5/wheel_bl_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: BL_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  /robot5/wheel_br_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: BR_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
#controller_joint_names: ['', 'BL_wheel_joint', 'BR_wheel_joint', 'FR_wheel_joint', 'FL_wheel_joint', ]
